### ISSUE TITLE
OpenRarity rank not calculating correctly on Skulptuur collection

### ISSUE THREAD

**Issue by tyoffice** [OpenRarity/open-rarity#114]
**Describe the bug**

**Information**
OpenRarity incorrectly calculating rarity.

* Collection link/name
Skulptuur by Piter Pasma (Art Blocks Curated collection) https://opensea.io/collection/skulptuur-by-piter-pasma
Skulptuur #118 has an OpenRarity rank of 975 on OpenSea and a rarity rank of 18 on Artacle. It is one of only 12 in the collection with a Camera Height = High. https://opensea.io/assets/ethereum/0xa7d8d9ef8d8ce8992df33d8b8cf4aebabd5bd270/173000118

* Contract standard
* Chain
Eth

**To Reproduce**
Steps to reproduce the behavior: Compare rarity rank betweek sites. Look at traits in collection. Camera heigh = high is the second rarest trait and rank should reflect that. 

**Expected behavior**
Recalculate rarity on this collection to accurately reflect traits.

**Screenshots**

**Environment**
 - Python [e.g. 3.10.3]
 - Library Version [e.g. 1.0]

**Additional context**

**Comment by impreso** [comment]
Hi thanks for reporting. This is not a bug and OR works as expected. I checked the collection and Camera Height = High  is not a unique trait.  Here are all assets with this trait:
https://opensea.io/collection/skulptuur-by-piter-pasma?search[sortAscending]=true&search[sortBy]=UNIT_PRICE&search[stringTraits][0][name]=camera_height&search[stringTraits][0][values][0]=high

We consider whole trait combination when we compute rarity not a single trait and this particular asset has much less rare traits in the combination.

**Comment by tyoffice** [comment]
Do you notice the rarity rank for all other assets with that trait? They are ranked 21-80. This is the only asset with that trait outside of that range and it's ranked 975. It also has a rare environment trait, which is why it should be among the rarest of that group.
