### ISSUE TITLE
Proposed fixes to the documentation 

### ISSUE THREAD

**Issue by RichardAwoyemi** [OpenRarity/open-rarity#52]
I've just tested this and spotted a couple of minor issues with the Gitbook documentation:
https://openrarity.gitbook.io/developers/quick-guides/integrating-openrarity-in-your-application

In the second code block (when leveraging the Opensea API):

The import:
`from open_rarity import Collection`

Should be:
`from open_rarity import RarityRanker`

And towards the bottom, when iterating through the results, the result must be dereferenced by `token` before accessing `token_identifier`.

So in all, the code block should look something more like this:

```
# OpenRarity version 0.4.0-beta
from open_rarity import RarityRanker
from open_rarity.resolver.opensea_api_helpers import (
    get_collection_from_opensea,
)

slug = 'proof-moonbirds'
# Create OpenRarity collection object from OpenSea API
collection = get_collection_from_opensea(slug)

# Generate scores for a collection
ranked_tokens = RarityRanker.rank_collection(collection=collection)

# Iterate over the ranked and sorted tokens
for token in ranked_tokens:
    token_id = token.token.token_identifier.token_id
    rank = token.rank
    score = token.score
    print(f"\tToken {token_id} has rank {rank} score: {score}")

```

**Comment by impreso** [comment]
Thanks for your bug report we will fix it asap!

**Comment by impreso** [comment]
Fixed in the documentation.
