### ISSUE TITLE
Allow user to control token batch size

### ISSUE THREAD

**Issue by matthieuoliveira** [OpenRarity/open-rarity#58]
**Is your feature request related to a problem? Please describe.**
Currently the  `get_collection_from_opensea` function variable `batch_size` is hard-coded to 30.

**Describe the solution you'd like**
I'd like a solution allowing a user to control this variable to speed up the processing.

**Additional context**
While the OS docs don't limit `token_ids` to a max length, the query results are capped at 50. Therefore, is it best to set this batch size to 50, or does the response return more than 50 assets given `token_ids` are set to a greater length? If there is no cap, then I think it's best to allow the user to decide the batch size and if there is a cap, then the batch size should be capped at the max length i.e 50.

**Comment by impreso** [comment]
@matthieuoliveira makes sense, i tried to call API with `batch_size` 50 and it's not supported. The maximum allowed `batch_size` is 30. I put together PR to propagate the property, to control the batch size on the client side.
