### ISSUE TITLE
Fetch Assets using GraphQL

### ISSUE THREAD

**Issue by emorling** [OpenRarity/open-rarity#62]
Now, that we are adding more and more to the Assets Endpoint, can the OpenRarity team use your Clout and have OpenSea open up their GraphQL to everyone? That way we can define exactly what fields we want to fetch. Thanks 😀

**Comment by impreso** [comment]
I don't think this ticket is for OpenRarity, but rather OpenSea feature request. I will follow up with the team offline , but will close this request , since we are not tracking OpenSea API items in this repo. Thanks for the idea!!
