### ISSUE TITLE
Missing Rarity Data?

### ISSUE THREAD

**Issue by emorling** [OpenRarity/open-rarity#63]
> Here is promised update with the OpenSea API that provides rarity data right now on the [Assets API endpoint](https://docs.opensea.io/reference/asset-object#rarity-data) . We are still figuring out how to support other languages than python, but this should give you a straight integration point for TS.

Should we expect collections to have rarity data? I made a quick test with a BAYC item here:

`https://opensea.io/assets/ethereum/0xbc4ca0eda7647a8ab7c2061c2e118a18a936f13d/5118`

However, the rarity data is null? Should this be expected?

**Comment by emorling** [comment]
I tried several other prominent collections, and all seem to be missing Rarity data.

**Comment by impreso** [comment]
Hi @emorling this is probably because they are not opt-in yet. We only show rarity data for Opt-in collections.

**Comment by emorling** [comment]
> Hi @emorling this is probably because they are not opt-in yet. We only show rarity data for Opt-in collections.

I see... so there is no standardized fallback?

**Comment by impreso** [comment]
Realistically just by running the library on your compute.

**Comment by emorling** [comment]
I was hoping we would have a rarity for all collections on OpenSea 😁

**Comment by impreso** [comment]
Yes, we are working on the coverage improvement.

**Comment by impreso** [comment]
Should we close it , since it's not a bug but rather works as intended :)

**Comment by chrysb** [comment]
@emorling You can check the collection endpoint of the OpenSea API and see if `is_rarity_enabled` is true
