### ISSUE TITLE
Blog announcement link broken

### ISSUE THREAD

**Issue by orionsolidified** [OpenRarity/open-rarity#96]
**Describe the bug**
Current blog announcement link is broken

**To Reproduce**
Visit Readme.md file

**Expected behavior**
Correct link: https://mirror.xyz/openrarity.eth/-R8ZA5KCMgqtsueySlruAhB77YBX6fSnS_dT-8clZPQ

**Comment by impreso** [comment]
Thanks for reporting - fixed.
